# Generated by Django 2.2.7 on 2019-11-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dawki',
            fields=[
                ('idDawki', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('wartosc', models.IntegerField()),
                ('sklad', models.CharField(max_length=300)),
                ('opis', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GrupyZywieniowe',
            fields=[
                ('idGrupyZywieniowej', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=500)),
                ('idDawki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadoBaza.Dawki')),
            ],
        ),
        migrations.CreateModel(
            name='Krowy',
            fields=[
                ('Numer', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('DataUrodzenia', models.DateField(verbose_name='data urodzenia')),
                ('rasa', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=500)),
                ('wydajnosc', models.IntegerField()),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadoBaza.GrupyZywieniowe')),
                ('matka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='krowa', to='stadoBaza.Krowy')),
                ('ojciec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='byk', to='stadoBaza.Krowy')),
            ],
        ),
        migrations.CreateModel(
            name='Krycia',
            fields=[
                ('idKrycia', models.AutoField(primary_key=True, serialize=False)),
                ('opis', models.CharField(max_length=500)),
                ('data', models.DateField(verbose_name='data krycia')),
                ('byk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stadoBaza.Krowy')),
                ('krowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stadoBaza.Krowy')),
            ],
        ),
    ]
