# Generated by Django 2.2.7 on 2020-01-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stadoBaza', '0002_krowy_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupyzywieniowe',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupyzywieniowe', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
